services:
  node: 
    build: .
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:8.0.35
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev

volumes:
  mysqldata:
